theme = "risotto"

baseURL = 'madsjensen.github.io'
languageCode = 'en-us'
title = 'weakAI'

[[menu.main]]
name = "Blog"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about/"
weight = 2


[caches.images]
dir = ':cacheDir/images'
